const ImagesUri = [
    {types:['חלבי','Dairy'],
    image:require("../assets/images/dairy-products.png")},
    {types:['בשרי','Meat'],
    image:require("../assets/images/meat-type.png")},
    {types:['גריל','Grill'],
    image:require("../assets/images/campfire.png")},
    {types:['המבורגרים','Hamburgers'],
    image:require("../assets/images/hamburger.png")},
    {types:['פיצריה','Pizza'],
    image:require("../assets/images/pizza.png")},
    {types:['בית קפה','Coffee Shop'],
    image:require("../assets/images/coffee.png")},
    {types:['דגים','Fish'],
    image:require("../assets/images/fish.png")},
    {types:['ארוחת בוקר','Breakfast'],
    image:require("../assets/images/breakfast.png")},
    {types:['ביתי','Homemade Food'],
    image:require("../assets/images/chicken.png")},
    {types:['בשרים','Meats'],
    image:require("../assets/images/meat.png")},
    {types:['טבעוני','Vegan'],
    image:require("../assets/images/diet.png")},
    {types:['צמחוני','Vegetarian'],
    image:require("../assets/images/vegan-food.png")},
    {types:['סושי','Sushi'],
    image:require("../assets/images/tuna.png")},
    {types:['איטלקי','Italian'],
    image:require("../assets/images/spaghetti.png")},
    {types:['אסייתי','Asian'],
    image:require("../assets/images/chinese-food.png")},
    {types:['פלאפל','Falafel'],
    image:require("../assets/images/falafel.png")},
    {types:['שווארמה','Shawarma'],
    image:require("../assets/images/kebab.png")},
    {types:['חומוס','Hummus'],
    image:require("../assets/images/hummus.png")},
    {types:['פאב-בר','bar-pub'],
    image:require("../assets/images/bar.png")},
    {types:['ים תיכוני','Mediterranean'],
    image:require("../assets/images/bruschetta.png")},
    {types:['מאפה','Bakery'],
    image:require("../assets/images/bread.png")},
    {types:['גלידרייה','Ice Cream'],
    image:require("../assets/images/ice-cream.png")},

];

export default ImagesUri;